# Generated by Django 3.1.2 on 2022-01-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaAlta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
