# Generated by Django 3.2 on 2022-02-01 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(default=None, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='foto',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='participa',
            name='fechaInscripcion',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='participa',
            name='idCliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participa',
            name='idProyecto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nucleo.proyectos'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='rol',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechafin',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechainicion',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='idCategoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nucleo.categorias'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='idEmpleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='nivel',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='titulo',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaNacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=None, verbose_name='cliente status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_empleado',
            field=models.BooleanField(default=None, verbose_name='empleado status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
