# Generated by Django 3.2 on 2022-02-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20220201_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='foto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participa',
            name='fechaInscripcion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='participa',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participa',
            name='idProyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.proyectos'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='rol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechafin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fechainicion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='idCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.categorias'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='idEmpleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='nivel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='titulo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(null=True, verbose_name='cliente status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_empleado',
            field=models.BooleanField(null=True, verbose_name='empleado status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
