# Generated by Django 3.1.2 on 2022-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20220112_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.SmallIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default=False, max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaAlta',
            field=models.DateField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='cliente status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_empleado',
            field=models.BooleanField(default=False, verbose_name='empleado status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='empleados',
        ),
    ]
