# Generated by Django 3.1.2 on 2022-02-03 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_user_fechaalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='informeFinal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaAlta',
            field=models.DateField(null=True, verbose_name=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
