# Generated by Django 3.1.2 on 2022-02-03 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20220203_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='fechainicion',
            new_name='fechainiciacion',
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaAlta',
            field=models.DateField(default=0, verbose_name=datetime.datetime.today, null=True),
            preserve_default=False,
        ),
    ]
