# Generated by Django 3.1.2 on 2022-02-03 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20220203_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaAlta',
            field=models.DateField(verbose_name=datetime.datetime.today),
        ),
    ]
