# Generated by Django 3.1.2 on 2022-02-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20220203_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='foto'),
        ),
    ]
